name: test12345
favicon: null
layout_spectrum: 0.9408450303599238
typography_spectrum: 0.007726171286776662
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#3C493F'
    - '#7E8D85'
    - '#B3BFB8'
    - '#F0F7F4'
    - '#A2E3C4'
  brandStrength: 0.3472119828220457
  lightness: 0.36009984998963773
  saturation: 0.060902895871549845
  rhythmicContrast: 0.8864103467203677
purpose: []
